# This is a basic workflow to help you get started with Actions

name: Clinic Cron Build

# Controls when the action will run. 
on:
  # Triggers the workflow every 1 AM
  # schedule:
  # - cron: "0 6 * * *"
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Build API service with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        run: cd svc-cron
        run: npm ci
        run: npm run build --if-present
      - name: Build Jovo voice service with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        run: cd voice-end
        run: npm ci
        run: npm run build --if-present
      
